-- MySQL Script generated by MySQL Workbench
-- Fri Nov 17 14:35:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(20) NOT NULL,
  `pw` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NULL,
  `authentication_status` TINYINT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`collections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`collections` (
  `collection_id` INT NOT NULL AUTO_INCREMENT,
  `collection_title` VARCHAR(50) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `users_user_id` INT NOT NULL,
  PRIMARY KEY (`collection_id`),
  INDEX `fk_collections_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_collections_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Content` (
  `content_id` INT NOT NULL AUTO_INCREMENT,
  `content_classify` TINYINT NULL,
  `content_name` VARCHAR(45) NULL,
  `Contentcol` VARCHAR(45) NULL,
  PRIMARY KEY (`content_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`authors` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `author_name` VARCHAR(45) NULL,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Livetalks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Livetalks` (
  `livetalk_id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(45) NULL,
  `chat_from` VARCHAR(45) NULL,
  `time` TIMESTAMP NULL,
  `Content_content_id` INT NOT NULL,
  PRIMARY KEY (`livetalk_id`),
  INDEX `fk_Livetalks_Content1_idx` (`Content_content_id` ASC) VISIBLE,
  CONSTRAINT `fk_Livetalks_Content1`
    FOREIGN KEY (`Content_content_id`)
    REFERENCES `mydb`.`Content` (`content_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chat` (
  `chat_id` INT NOT NULL AUTO_INCREMENT,
  `Livetalks_livetalk_id1` INT NOT NULL,
  `users_user_id1` INT NOT NULL,
  INDEX `fk_Livetalks_has_users_Livetalks2_idx` (`Livetalks_livetalk_id1` ASC) VISIBLE,
  INDEX `fk_Livetalks_has_users_users2_idx` (`users_user_id1` ASC) VISIBLE,
  PRIMARY KEY (`chat_id`),
  CONSTRAINT `fk_Livetalks_has_users_Livetalks2`
    FOREIGN KEY (`Livetalks_livetalk_id1`)
    REFERENCES `mydb`.`Livetalks` (`livetalk_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livetalks_has_users_users2`
    FOREIGN KEY (`users_user_id1`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`follow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`follow` (
  `follow_id` INT NOT NULL AUTO_INCREMENT,
  `users_user_id` INT NOT NULL,
  `users_user_id1` INT NOT NULL,
  PRIMARY KEY (`follow_id`, `users_user_id`, `users_user_id1`),
  INDEX `fk_users_has_users_users2_idx` (`users_user_id1` ASC) VISIBLE,
  INDEX `fk_users_has_users_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_users_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users2`
    FOREIGN KEY (`users_user_id1`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`filter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`filter` (
  `slang_id` INT NOT NULL AUTO_INCREMENT,
  `slang_content` VARCHAR(45) NULL,
  PRIMARY KEY (`slang_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`email authentication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`email authentication` (
  `authentication_id` INT NOT NULL AUTO_INCREMENT,
  `authentication_code` INT NOT NULL,
  `Request_time` TIME NULL,
  `Completion_time` TIME NULL,
  `users_user_id` INT NOT NULL,
  PRIMARY KEY (`authentication_id`, `users_user_id`),
  INDEX `fk_email authentication_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_email authentication_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manage_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manage_content` (
  `manage_content_id` INT NOT NULL AUTO_INCREMENT,
  `collections_collection_id1` INT NOT NULL,
  `Content_content_id` INT NOT NULL,
  INDEX `fk_collections_has_Product_collections2_idx` (`collections_collection_id1` ASC) VISIBLE,
  INDEX `fk_collections_has_Product_Product2_idx` (`Content_content_id` ASC) VISIBLE,
  PRIMARY KEY (`manage_content_id`),
  CONSTRAINT `fk_collections_has_Product_collections2`
    FOREIGN KEY (`collections_collection_id1`)
    REFERENCES `mydb`.`collections` (`collection_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_collections_has_Product_Product2`
    FOREIGN KEY (`Content_content_id`)
    REFERENCES `mydb`.`Content` (`content_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`own`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`own` (
  `own_id` INT NOT NULL AUTO_INCREMENT,
  `Product_product_id` INT NOT NULL,
  `authors_author_id` INT NOT NULL,
  PRIMARY KEY (`own_id`, `Product_product_id`, `authors_author_id`),
  INDEX `fk_Product_has_authors_authors1_idx` (`authors_author_id` ASC) VISIBLE,
  INDEX `fk_Product_has_authors_Product1_idx` (`Product_product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_authors_Product1`
    FOREIGN KEY (`Product_product_id`)
    REFERENCES `mydb`.`Content` (`content_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_authors_authors1`
    FOREIGN KEY (`authors_author_id`)
    REFERENCES `mydb`.`authors` (`author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manage_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`manage_category` (
  `manage_category_id` INT NOT NULL AUTO_INCREMENT,
  `categories_category_id` INT NOT NULL,
  `Content_content_id` INT NOT NULL,
  PRIMARY KEY (`manage_category_id`, `categories_category_id`, `Content_content_id`),
  INDEX `fk_categories_has_Content_Content1_idx` (`Content_content_id` ASC) VISIBLE,
  INDEX `fk_categories_has_Content_categories1_idx` (`categories_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_categories_has_Content_categories1`
    FOREIGN KEY (`categories_category_id`)
    REFERENCES `mydb`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories_has_Content_Content1`
    FOREIGN KEY (`Content_content_id`)
    REFERENCES `mydb`.`Content` (`content_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `cooment_id` INT NOT NULL AUTO_INCREMENT,
  `users_user_id` INT NOT NULL,
  `Content_content_id` INT NOT NULL,
  `comment_content` VARCHAR(200) NULL,
  INDEX `fk_users_has_Content_users1_idx` (`users_user_id` ASC) VISIBLE,
  INDEX `fk_users_has_Content_Content1_idx` (`Content_content_id` ASC) VISIBLE,
  PRIMARY KEY (`cooment_id`),
  CONSTRAINT `fk_users_has_Content_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_Content_Content1`
    FOREIGN KEY (`Content_content_id`)
    REFERENCES `mydb`.`Content` (`content_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rate` (
  `rate_id` INT NOT NULL AUTO_INCREMENT,
  `users_user_id` INT NOT NULL,
  `Content_content_id` INT NOT NULL,
  `rate` INT NULL DEFAULT NULL,
  INDEX `fk_users_has_Content1_users1_idx` (`users_user_id` ASC) VISIBLE,
  INDEX `fk_users_has_Content1_Content1_idx` (`Content_content_id` ASC) VISIBLE,
  PRIMARY KEY (`rate_id`),
  CONSTRAINT `fk_users_has_Content1_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `mydb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_Content1_Content1`
    FOREIGN KEY (`Content_content_id`)
    REFERENCES `mydb`.`Content` (`content_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
